version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: crowdfunding-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-crowdfunding}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: crowdfunding-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  vault:
    image: hashicorp/vault:latest
    container_name: crowdfunding-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN:-dev-root-token}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file
    command: server -dev
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: crowdfunding-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: crowdfunding-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: crowdfunding-kafka
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@crowdfunding-kafka:29093
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://crowdfunding-kafka:9092
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     CLUSTER_ID: ${CLUSTER_ID}
  #   ports:
  #     - "127.0.0.1:9092:9092"
  #     - "29092:29092"
  #   restart: unless-stopped

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: crowdfunding-kafka-ui
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - kafka
  #   restart: unless-stopped

volumes:
  postgres-data:
    driver: local
  vault-data:
    driver: local
  grafana-data:
    driver: local
